### ISSUE TITLE
Try sim data on spade

### ISSUE THREAD

**Issue by vict0rsch** [cc-ai/MUNIT#25]

**Comment by vict0rsch** [comment]
@51N84D can you add the link to the comet experiment?

**Comment by 51N84D** [comment]
@vict0rsch sure, here you go: https://www.comet.ml/sunandr/testing-munit/3a80d5d87dba4c58bf167e76daa03098

<blockquote><img src="https://www.comet.ml/images/meta/google-card.png" width="48" align="right"><div>Comet.ml - Supercharging Machine Learning</div><div><strong><a href="https://www.comet.ml/sunandr/testing-munit/3a80d5d87dba4c58bf167e76daa03098">Comet.ml - Supercharging Machine Learning</a></strong></div><div>Comet lets you track code, experiments, and results on ML projects. It’s fast, simple, and free for open source projects.</div></blockquote>
